################################################################################
# 02-plot_histology-specific_splicing_events.R
# 
# Plots UpsetR plots based on splicing events generated by the 
# 
# written by Ammar Naqvi
#
# usage: Rscript 02-plot_histology-specific_splicing_events.R
################################################################################

## libraries 
suppressPackageStartupMessages({
  library("ggplot2")
  library("UpSetR")
  library("vroom")
  library("tidyverse")
})

#Get `magrittr` pipe
`%>%` <- dplyr::`%>%`

##set up directories
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "histology-specific-splicing")
results_dir <- file.path(analysis_dir, "results")

plots_dir <- file.path(analysis_dir, "plots")
if(!dir.exists(plots_dir)){
  dir.create(plots_dir, recursive=TRUE)
}

# input file for colors
palette_file <- file.path(data_dir, "histologies-plot-group.tsv")

## output files for final plots
upsetR_plot_file <- file.path(analysis_dir, "plots", "upsetR_histology-specific.pdf")
uniq_tsv_out <- file.path(results_dir, "unique_events.tsv")

# Load the data using vroom
palette_df <- read_tsv(palette_file)
splice_event_df <- vroom::vroom(file.path(results_dir, "recurrent_splice_events_by_histology.tsv"), delim = "\t", trim_ws = TRUE, col_names = TRUE)

## make list out of all events
list_for_upsetR <- splice_event_df %>%
  dplyr::mutate(event_type = paste(splicing_event, type, sep = "_")) %>%
  dplyr::select(histology, event_type) %>%
  group_by(histology) %>%
  summarise(splicing_events = list(event_type)) %>% # Summarize as a list
  ungroup() %>%
  deframe() 
  
# Adjust the space allocated for numbers on the bars
#upset_text_scale <- 1.2  # Increase this value to allocate more space for the numbers
#upset_point_size <- 3 

# get plot colors
# color palette for histology
uniq_plot_cols <- palette_df %>%
  select(plot_group, plot_group_hex) %>%
  unique()

cols <- uniq_plot_cols$plot_group_hex
names(cols) <- uniq_plot_cols$plot_group
# order the names to match the upsetR plot names so the colors match correctly
# Calculate frequencies
histology_frequencies <- splice_event_df %>%
  count(histology) %>%
  arrange(desc(n))

# Reorder cols based on this frequency order
ordered_histologies <- histology_frequencies$histology
cols <- cols[ordered_histologies]

events <- upset(fromList(list_for_upsetR), 
      keep.order = TRUE, 
      mainbar.y.label = "", 
      main.bar.color = "black",
      sets.bar.color = cols,
      order.by = "freq", 
      sets.x.label = "Set size",
      mb.ratio = c(0.5, 0.5), 
      shade.color = "aliceblue",
      #text scale
      # c(intersection size title, intersection size tick labels, set size title, set size tick labels, set names, numbers above bars)
      text.scale = c(2,2,2,1.3,1.7,0), 
      point.size = 3, 
      line.size = 1.2,  
      nsets = 17, 
      empty.intersections = "on")

# Generate the UpSetR plot
# Save plot
pdf(upsetR_plot_file, height = 8, width = 10)
print(events)
dev.off()


# Create an empty list to store the results
unique_items_list <- vector("list", length(list_for_upsetR))

# Loop through each sublist and find unique items
for (i in seq_along(list_for_upsetR)) {
  current_sublist <- unlist(list_for_upsetR[[i]])
  other_sublists <- unlist(list_for_upsetR[-i])
  unique_items <- current_sublist[!(current_sublist %in% other_sublists)]
  histology = names(list_for_upsetR)[i]
  unique_items_list[[histology]] <- unique_items
}

# Iterate through the sub-lists and create one larger list to write to a TSV file
unique_events_df <- data.frame()
for (Histology in names(unique_items_list)) {
  
  # Create a data frame with list values
  df <- data.frame(SpliceID=unlist(unique_items_list[[Histology]])) %>% mutate(Histology=paste(Histology,sep="")) 
  
  # append to larger df of unique events
  unique_events_df <- rbind(unique_events_df,df)
  
}
write_tsv(unique_events_df, uniq_tsv_out)

