################################################################################
# 03-plot-histology-specific-norm-events.R
# 
# Plots UpsetR plots based on splicing events generated by the 
# 
# written by Ammar S. Naqvi, Ryan J. Corbett, Jo Lynne Rokita
#
# usage: Rscript 03-plot-histology-specific-norm-events.R
################################################################################

## libraries 
suppressPackageStartupMessages({
  library("ggplot2")
  library("UpSetR")
  library("vroom")
  library("tidyverse")
})

#Get `magrittr` pipe
`%>%` <- dplyr::`%>%`

##set up directories
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "histology-specific-splicing")
results_dir <- file.path(analysis_dir, "results")

plots_dir <- file.path(analysis_dir, "plots")
if(!dir.exists(plots_dir)){
  dir.create(plots_dir, recursive=TRUE)
}

## theme for all plots
figures_dir <- file.path(root_dir, "figures")
source(file.path(figures_dir, "theme_for_plots.R"))

# input file for colors
palette_file <- file.path(data_dir, "histologies-plot-group.tsv")
event_file <- file.path(results_dir, "unique_events.tsv")

## filter and count histologies
hist_df <- vroom(palette_file) %>%
  filter(experimental_strategy == "RNA-Seq") %>%
  count(plot_group) %>%
  rename(Total = n)

events <- vroom(event_file) %>% 
  rename(plot_group=Histology) %>% 
  extract(SpliceID, into = c("Case", "SpliceID", "Event"), regex = "^(.*)=(.*)_(inclusion|skipping)$")
  
## inclusion vs skipping
incl_skip <- events %>% 
  mutate(Event = str_to_title(Event)) %>%
  count(plot_group, Event) %>%
  rename(unique_hits = n) %>%
  inner_join(hist_df, by='plot_group') %>%
  mutate(norm_unique = unique_hits / Total)

# Sort the data frame in descending order by avg_unique of Skipping events
group_order <- incl_skip %>%
  group_by(plot_group) %>%
  summarise(norm_unique_total = sum(norm_unique)) %>%
  arrange(norm_unique_total) %>%
  pull(plot_group)

# Create the side-by-side bar plot with custom colors
incl_uniq_plot <- ggplot(incl_skip, aes(x = fct_relevel(plot_group, group_order), y = norm_unique, fill = Event)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_fill_manual(name = "Splicing Event", values = c(Skipping = "#0C7BDC", Inclusion = "#FFC20A"))+   labs(x = "Histology",
       y = "Unique Recurrent\nSplice Events per Patient") +
  theme_Publication() + 
  ylim(c(0,max(incl_skip$norm_unique)+2))+
  coord_flip()+
  theme(legend.position = "top",
        legend.direction = "horizontal")

# Save plot
pdf(file.path(plots_dir,"norm-uniq-hits-inclusion-or-skipping.pdf"), height = 7, width = 7)
print(incl_uniq_plot)
dev.off()


## splicing cases
splicing_case <- events %>% 
  count(plot_group, Case) %>%
  rename(unique_hits = n) %>%
  inner_join(hist_df, by='plot_group') %>%
  mutate(norm_unique = unique_hits / Total,
         Case = factor(Case, levels = c("RI", "A5SS", "A3SS", "SE")))

group_order <- splicing_case %>%
  group_by(plot_group) %>%
  summarise(norm_unique_total = sum(norm_unique)) %>%
  arrange(norm_unique_total) %>%
  pull(plot_group)

# Create the side-by-side bar plot with custom colors
case_uniq_plot <- ggplot(splicing_case, aes(x = fct_relevel(plot_group, group_order), y = norm_unique, fill = Case)) +
  geom_bar(stat = "identity", position = position_stack()) +
  scale_fill_manual(name = "Splicing Case", values = c(SE = "#0C7BDC", RI = "#00A5A5", A3SS = "#FFC20A", A5SS = "#E04C2F"))+ 
  labs(x = "Histology",
       y = "Unique Recurrent\nSplice Events per Patient") +
  theme_Publication() + 
  coord_flip()+
  theme(legend.position = c(0.4, 1.04), # shift legend to the left to fit
        legend.direction = "horizontal") +
  guides(fill = guide_legend(reverse = TRUE))

# Save plot
pdf(file.path(plots_dir,"norm-uniq-hits-case.pdf"), height = 7, width = 7)
print(case_uniq_plot)
dev.off()

